name: landuse-construction-check-date.yaml

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [build]
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1,3,5'

jobs:
  build:
    name: Build json data
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install requirements
      run: |
        [ -d data ] || mkdir data
        sudo apt install s3cmd
        echo '
        [default]
        access_key = ${{ secrets.AWS_ACCESS_KEY_ID }}
        access_token =
        add_encoding_exts =
        add_headers =
        bucket_location = us-east-005
        ca_certs_file =
        cache_file =
        check_ssl_certificate = True
        check_ssl_hostname = True
        cloudfront_host = cloudfront.amazonaws.com
        connection_max_age = 5
        connection_pooling = True
        content_disposition =
        content_type =
        default_mime_type = binary/octet-stream
        delay_updates = False
        delete_after = False
        delete_after_fetch = False
        delete_removed = False
        dry_run = False
        enable_multipart = True
        encoding = UTF-8
        encrypt = False
        expiry_date =
        expiry_days =
        expiry_prefix =
        follow_symlinks = False
        force = False
        get_continue = False
        gpg_command = /usr/bin/gpg
        gpg_decrypt = %(gpg_command)s -d --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
        gpg_encrypt = %(gpg_command)s -c --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
        gpg_passphrase = ${{ secrets.AWS_ACCESS_KEY_ID }}
        guess_mime_type = True
        host_base = s3.us-east-005.backblazeb2.com
        host_bucket = %(bucket)s.s3.us-east-005.backblazeb2.com
        human_readable_sizes = False
        invalidate_default_index_on_cf = False
        invalidate_default_index_root_on_cf = True
        invalidate_on_cf = False
        kms_key =
        limit = -1
        limitrate = 0
        list_md5 = False
        log_target_prefix =
        long_listing = False
        max_delete = -1
        mime_type =
        multipart_chunk_size_mb = 15
        multipart_copy_chunk_size_mb = 1024
        multipart_max_chunks = 10000
        preserve_attrs = True
        progress_meter = True
        proxy_host =
        proxy_port = 0
        public_url_use_https = False
        put_continue = False
        recursive = False
        recv_chunk = 65536
        reduced_redundancy = False
        requester_pays = False
        restore_days = 1
        restore_priority = Standard
        secret_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        send_chunk = 65536
        server_side_encryption = False
        signature_v2 = False
        signurl_use_https = False
        simpledb_host = sdb.amazonaws.com
        skip_existing = False
        socket_timeout = 300
        ssl_client_cert_file =
        ssl_client_key_file =
        stats = False
        stop_on_error = False
        storage_class =
        throttle_max = 100
        upload_id =
        urlencoding_mode = normal
        use_http_expect = False
        use_https = True
        use_mime_magic = True
        verbosity = WARNING
        website_endpoint = http://%(bucket)s.s3-website-%(location)s.amazonaws.com/
        website_error =
        website_index = index.html
        ' > ~/.s3cfg

    - name: build-json-data
      run: |
          python -m venv env 
          source ./env/bin/activate
          pip install -r requirements.txt
          python landuse-construction-check-date.py > ./data/landuse-construction-check-date.json
          ls -al ./data
          ls -al ~/.s3cfg

    - name: Copy artifacts to BackBlaze/S3 bucket
      env:
        S3_BUCKET: ${{ secrets.TILES_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        ls -al ~/.s3cfg
        s3cmd ls s3://osmie-tiles
        echo "----"
        s3cmd put --force ./data/landuse-construction-check-date.json s3://osmie-tiles/reports/data/landuse-construction-check-date.json
        s3cmd put --force ./web_files/index.html s3://osmie-tiles/reports/index.html
        s3cmd put --force ./web_files/landuse-construction-check-date.html s3://osmie-tiles/reports/landuse-construction-check-date.html
